### ISSUE TITLE
[BUG]AudioQuality Error

### ISSUE THREAD

**Issue by Pranavprana** [kokarare1212/librespot-python#125]
File "C:\Python39\lib\enum.py", line 352, in __getattr__
    raise AttributeError(name) from None
AttributeError: AudioQuality

**Comment by kokarare1212** [comment]
Please provide the code that reproduces the problem.

**Comment by Pranavprana** [comment]
from librespot.core import Session
from librespot.metadata import TrackId
from librespot.audio.decoders import AudioQuality, VorbisOnlyAudioQuality

session = Session.Builder() \
    .user_pass("Username", "Password") \
    .create()

track_id = TrackId.from_uri("spotify:track:xxxxxxxxxxxxxxxxxxxxxx")
stream = session.content_feeder().load(track_id, VorbisOnlyAudioQuality(AudioQuality.VERY_HIGH), False, None)
stream.input_stream.stream().read()
######################################################################

Audio key error, code: 1
Audio key error, code: 1
Traceback (most recent call last):
  File "C:\Users\A.T\PycharmProjects\SPotiDESKaio\test.py", line 17, in <module>
    stream = session.content_feeder().load(track_id, VorbisOnlyAudioQuality(AudioQuality.VERY_HIGH), False, None)
  File "C:\Users\A.T\PycharmProjects\SPotiDESKaio\librespot\audio\__init__.py", line 717, in load
    return self.load_track(playable_id, audio_quality_picker, preload,
  File "C:\Users\A.T\PycharmProjects\SPotiDESKaio\librespot\audio\__init__.py", line 778, in load_track
    return self.load_stream(file, track, None, preload, halt_listener)
  File "C:\Users\A.T\PycharmProjects\SPotiDESKaio\librespot\audio\__init__.py", line 732, in load_stream
    return CdnFeedHelper.load_track(self.__session, track, file,
  File "C:\Users\A.T\PycharmProjects\SPotiDESKaio\librespot\audio\__init__.py", line 335, in load_track
    key = session.audio_key().get_audio_key(track.gid, file.file_id)
  File "C:\Users\A.T\PycharmProjects\SPotiDESKaio\librespot\audio\__init__.py", line 277, in get_audio_key
    return self.get_audio_key(gid, file_id, False)
  File "C:\Users\A.T\PycharmProjects\SPotiDESKaio\librespot\audio\__init__.py", line 278, in get_audio_key
    raise RuntimeError(
RuntimeError: Failed fetching audio key! gid: c2de18c6ab584f27bfbd42893dd7d7ca, fileId: 059df821cead0cde67b1e88a47ae87d05b6b5c3c

**Comment by Pranavprana** [comment]
i did normal no error
 but can u guide me on what should I use to get music played from it
 running this code just complete without any error

**Comment by kokarare1212** [comment]
Music can be played by using external applications.
e.g. FFplay * not tested
```python
import subprocess

proc = subprocess.Popen(["/path/to/ffplay", "-"], stdin=subprocess.PIPE)
proc.communicate(input=stream.input_stream.stream().read())
```

**Comment by Pranavprana** [comment]
thankyou!
