### ISSUE TITLE
[BUG] 404 when calling get_metadata_4_album()

### ISSUE THREAD

**Issue by sesseor** [kokarare1212/librespot-python#172]
https://github.com/kokarare1212/librespot-python/blob/0db444f3bd97112024b8b680033667ba407ab2ae/librespot/core.py#L120

code return this : 
`<librespot.metadata.AlbumId object at 0x7f62693668c0>
Traceback (most recent call last):
  File "/workspaces/spotify-downloader/instence.py", line 10, in <module>
    print(session.api().get_metadata_4_album(track_id))
  File "/home/codespace/.python/current/lib/python3.10/site-packages/librespot/core.py", line 124, in get_metadata_4_album
    ApiClient.StatusCodeException.check_status(response)
  File "/home/codespace/.python/current/lib/python3.10/site-packages/librespot/core.py", line 206, in check_status
    raise ApiClient.StatusCodeException(response)
librespot.core.ApiClient.StatusCodeException: 404`

when calling get_metadata_4_album()

also my code :`session.api().get_metadata_4_album(AlbumId.from_uri("spotify:album:3HHNR44YbP7XogMVwzbodx"))`

**Comment by kokarare1212** [comment]
It was an implementation issue with AlbumId.

**Comment by sesseor** [comment]
looks good to me !
