### ISSUE TITLE
[BUG] BadCredentials

### ISSUE THREAD

**Issue by hazycora** [kokarare1212/librespot-python#277]
**Describe the bug**
Login fails on *some* accounts on *some* devices. My current guess is they're doing some kind of A/B test to phase out something this relies on? Maybe the protocol version needs to be updated?
Occurs not just here but also on the separate [librespot-js](https://npmjs.com/package/librespot) project and [librespot-java](https://github.com/librespot-org/librespot-java/issues/921). The bug is not with some library-specific logic but with a change to Spotify- a fix here will likely also be able to be applied everywhere else.

**To Reproduce**
```python
from librespot.core import Session

session = Session.Builder() \
    .user_pass("username", "password") \
    .create()
```

**Expected behavior**
The login should be successful.

**Screenshots**
```sh
Traceback (most recent call last):
  File "/home/hazy/tmp_a/test.py", line 7, in <module>
    .create()
     ^^^^^^^^
  File "/home/hazy/tmp_a/venv/lib/python3.12/site-packages/librespot/core.py", line 1634, in create
    session.authenticate(self.login_credentials)
  File "/home/hazy/tmp_a/venv/lib/python3.12/site-packages/librespot/core.py", line 939, in authenticate
    self.__authenticate_partial(credential, False)
  File "/home/hazy/tmp_a/venv/lib/python3.12/site-packages/librespot/core.py", line 1350, in __authenticate_partial
    raise Session.SpotifyAuthenticationException(ap_login_failed)
librespot.core.Session.SpotifyAuthenticationException: BadCredentials
```

**Client Information (please complete the following information):**
 - OS: Arch Linux
 - Python Version: 3.12.4
 - Library Version: Last snapshot (3b46fe560ad829b976ce63e85012cff95b1e0bf3)

**Comment by hazycora** [comment]
If it can't be reproduced, I have a server that has this problem, and I'm up for helping in any way I can!

**Comment by kokarare1212** [comment]
I don't know the details, I suspect that your IP address has been blacklisted due to the number of login attempts?

**Comment by hazycora** [comment]
given that this occurred the only time I had ever tried on this server, no I don't believe that

**Comment by shayanmaher** [comment]
> I don't know the details, I suspect that your IP address has been blacklisted due to the number of login attempts?

also i have this issue for login auth with this error `raise Session.SpotifyAuthenticationException(ap_login_failed)
librespot.core.Session.SpotifyAuthenticationException: BadCredentials`

**Comment by pdtan** [comment]
I also got this error sometimes

**Comment by shayanmaher** [comment]
> I also got this error sometimes

i solve this problem it belongs to ip of datacenters which in blacklist popular Datacenters like hetzener,...etc has this problem you can solve this issue by use a fresh ip

**Comment by staniel359** [comment]
@kokarare1212 I've started to encounter this too.

**Comment by IVIanuu** [comment]
I also encounter this issue since today.. Any fix?

**Comment by phuketbinaryt** [comment]
Same issue here with the bad credentials.

**Comment by dylenthomas** [comment]
This just started happening to me today too, might be an issue with spotify's client? I tried on a MacBook with latest MacOS and my linux desktop, both having same issue. I also tried with the latest install of librespot, that was working yesterday. 

Since this is happening to so many people they might have an issue with their api right now?

**Comment by clemwo** [comment]
I also have this issue on a windows machine.

It's also being discussed in the librespot project directly here : https://github.com/librespot-org/librespot/issues/1308

Feels like spotify changed something on their end maybe?

**Comment by rgon** [comment]
> i solve this problem it belongs to ip of datacenters which in blacklist popular Datacenters like hetzener,...

@shayanmaher happening to me on a residential IP. Definitely not data center blacklisting, but rather seems like a buggy rolled-out deploy in their end or rather some of their pesky A/B API testing

**Comment by hazycora** [comment]
> > I also got this error sometimes
> 
> i solve this problem it belongs to ip of datacenters which in blacklist popular Datacenters like hetzener,...etc has this problem you can solve this issue by use a fresh ip

this is not true. happens on all residential IPs ive tried now. that was absolutely just part of the rollout.

**Comment by TreeOfSelf** [comment]
Happening to me as well.

**Comment by kokarare1212** [comment]
It appears that login using username and password has been discontinued.
https://github.com/librespot-org/librespot-java/issues/921#issuecomment-2258440907
Please use other login methods (e.g. zeroconf) or PR a new login method instead.

**Comment by staniel359** [comment]
@kokarare1212 Could you then provide the instructions on how to use Zeroconf instead of Session?

**Comment by realCmdData** [comment]
Same issue for me, even changing IP's through a VPN doesn't work. 

```
  File "C:\Users\myusername\AppData\Local\Programs\Python\Python310\lib\site-packages\librespot\core.py", line 1350, in __authenticate_partial
    raise Session.SpotifyAuthenticationException(ap_login_failed)
librespot.core.Session.SpotifyAuthenticationException: BadCredentials
```

**Comment by realCmdData** [comment]
> Same issue for me, even changing IP's through a VPN doesn't work.
> 
> ```
>   File "C:\Users\myusername\AppData\Local\Programs\Python\Python310\lib\site-packages\librespot\core.py", line 1350, in __authenticate_partial
>     raise Session.SpotifyAuthenticationException(ap_login_failed)
> librespot.core.Session.SpotifyAuthenticationException: BadCredentials
> ```

UPDATE:

Got it to work... Somehow... Still not quite sure how but I tried restarting my PC and deactivating my VPN, and it worked. Perhaps through trial and error? Or Spotify is blocking CLI requests that come from known VPN servers? I have no idea...

**Comment by pdtan** [comment]
> Please use other login methods (e.g. zeroconf) 

Please provide the instructions on how to use Zeroconf instead of Session?

**Comment by kokarare1212** [comment]
https://github.com/kokarare1212/librespot-python#use-zeroconf-for-login
`zeroconf._ZeroconfServer__session`

**Comment by pdtan** [comment]
> https://github.com/kokarare1212/librespot-python#use-zeroconf-for-login `zeroconf._ZeroconfServer__session`

Very unclear. btw, I don't see `__ZeroconfSever__session`:
`[INFO     09:58:35] Zeroconf HTTP server started successfully on port 58172!
[DEBUG    09:58:35] Using selector: EpollSelector
{'_ZeroconfServer__inner': <librespot.zeroconf.ZeroconfServer.Inner object at 0xffff8c9e2760>, '_ZeroconfServer__keys': <librespot.crypto.DiffieHellman object at 0xffff8c991f10>, '_ZeroconfServer__runner': <librespot.zeroconf.ZeroconfServer.HttpRunner object at 0xffff8c4a09d0>, '_ZeroconfServer__zeroconf': <zeroconf._core.Zeroconf object at 0xffff8c4a0c10>, '_ZeroconfServer__service_info': ServiceInfo(type='_spotify-connect._tcp.local.', name='librespot-python._spotify-connect._tcp.local.', addresses=[b'@nE\x8d'], port=58172, weight=0, priority=0, server='mail.', properties={b'CPath': b'/', b'VERSION': b'1.0', b'STACK': b'SP'}, interface_index=None)}
[DEBUG    09:58:36] Using selector: EpollSelector`

**Comment by staniel359** [comment]
> https://github.com/kokarare1212/librespot-python#use-zeroconf-for-login `zeroconf._ZeroconfServer__session`

That's not an instruction.

**Comment by kingosticks** [comment]
> > https://github.com/kokarare1212/librespot-python#use-zeroconf-for-login `zeroconf._ZeroconfServer__session`
> 
> Very unclear. btw, I don't see `_ZeroconfServer__session`:
> 
> ```
> [INFO     09:58:35] Zeroconf HTTP server started successfully on port 58172!
> [DEBUG    09:58:35] Using selector: EpollSelector
> {'_ZeroconfServer__inner': <librespot.zeroconf.ZeroconfServer.Inner object at 0xffff8c9e2760>, '_ZeroconfServer__keys': <librespot.crypto.DiffieHellman object at 0xffff8c991f10>, '_ZeroconfServer__runner': <librespot.zeroconf.ZeroconfServer.HttpRunner object at 0xffff8c4a09d0>, '_ZeroconfServer__zeroconf': <zeroconf._core.Zeroconf object at 0xffff8c4a0c10>, '_ZeroconfServer__service_info': ServiceInfo(type='_spotify-connect._tcp.local.', name='librespot-python._spotify-connect._tcp.local.', addresses=[b'@nE\x8d'], port=58172, weight=0, priority=0, server='mail.', properties={b'CPath': b'/', b'VERSION': b'1.0', b'STACK': b'SP'}, interface_index=None)}
> [DEBUG    09:58:36] Using selector: EpollSelector
> ```

Forgive me for jumping in, but you have to actually use the zeroconf server to auth a client before a session will be created. Given the log you provided, it doesn't look like you did that.

**Comment by sn0am** [comment]
@pdtan or anyone else trying to get credentials.json via the zeroconf method, here's how I did it. I'll try to put it in simple terms so anyone without too much expertise can recreate.

Multiple ways to go about this, the easiest would be to get an IDE on a linux machine, I used pycharm community edition. Create a new project, sure your interpreter is python 3.8 and pip install librespot. 
(The reason for Python 3.8 is that I was getting errors on Python 3.10 and above. And the reason for using linux is that I was getting OS errors when trying to create a socket on Windows. I'm sure the errors could be resolved but this was faster)

Finally, use the sample code to get something like this and run the code
![Screenshot from 2024-08-12 21-46-02](https://github.com/user-attachments/assets/fe3704d8-93e9-49b5-9519-e3ff4b0917bf)

Now on the same machine, open the official spotify app and look for connect device to show as below

![libre](https://github.com/user-attachments/assets/ec2fcc41-f49b-4179-bdbe-a72928d13dd8)

Click on the librespot device and wait, you will see your credentials.json file generated in the project directory like so

![cred](https://github.com/user-attachments/assets/2542bf9c-0e4d-492e-9f7a-3ef3d5afd103)

**Comment by dracarys69** [comment]
idk about you guys i can still login fine with email and password and whenever i get BadCredentials  issue i delete the credentials json and change my account password and it starts working again. tho its been a while since i had that issue

**Comment by g42ftw** [comment]
**Login with username/password via `.user_pass()` method is no longer possible: https://github.com/librespot-org/librespot/issues/1308#issuecomment-2276196094**

> Please provide the instructions on how to use Zeroconf instead of Session?

@pdtan you may use [this very sketchy code](https://gist.github.com/g42ftw/b61304497cb19564e89f50197cf4d730) to generate credentials file to use further. Notice that device running the script should be on the same network as a desktop client in order to transfer playback or/and grab session

Use `.stored_file()` method instead or `.user_pass()` on [session builder stage](https://github.com/kokarare1212/librespot-python?tab=readme-ov-file#get-spotifys-oauth-token) to load login credentials from local file:
```python
session = Session.Builder() \
    .stored_file() \
    .create()
```
It should use `credentials.json` from current working directory by default.

**Comment by clemwo** [comment]
> **Login with username/password via `.user_pass()` method is no longer possible: [librespot-org/librespot#1308 (comment)](https://github.com/librespot-org/librespot/issues/1308#issuecomment-2276196094)**
> 
> > Please provide the instructions on how to use Zeroconf instead of Session?
> 
> @pdtan you may use [this very sketchy code](https://gist.github.com/g42ftw/b61304497cb19564e89f50197cf4d730) to generate credentials file to use further. Notice that device running the script should be on the same network as a desktop client in order to transfer playback or/and grab session
> 
> Use `.stored_file()` method instead or `.user_pass()` on [session builder stage](https://github.com/kokarare1212/librespot-python?tab=readme-ov-file#get-spotifys-oauth-token) to load login credentials from local file:
> 
> ```python
> session = Session.Builder() \
>     .stored_file() \
>     .create()
> ```
> 
> It should use `credentials.json` from current working directory by default.

Cool beans, that works.

Question: do the credentials expire? 
I want to run librespot in a docker container and maybe transfering playback once would be fine. 
But if the token expired every few days that would be an issue for me. 

I assume that t

**Comment by g42ftw** [comment]
> Question: do the credentials expire?

@clemwo they don't expire, unless you change your password or Spotify does. Successful login with zeroconf should always return the same long-live credentials that `.user_pass` always did (username+credentials blob).

The Spotify desktop client stores account login data in the client configuration file in a similar way:

<details>
<summary>.config/Spotify/prefs</summary>

```ini
autologin.blob="BLOB"
autologin.saved_credentials="{"USERNAME": ["USERNAME", "BLOB"]}"
```

</details>

**Comment by pdtan** [comment]
@clemwo thanks, but I use credentials.json from start, sometimes BadCredentials still happended, not usual. If using zeroconf to only create credentials.json, I actually don't need it.

**Comment by sertraline** [comment]
On Windows (this works on Linux) trying to use zeroconf results in the following:

```
WARNING:zeroconf:Error with socket 696 (('0.0.0.0', 5353))): [WinError 87] The parameter is incorrect
Traceback (most recent call last):
  File "C:\Users\sertraline\AppData\Local\Programs\Python\Python312\Lib\asyncio\proactor_events.py", line 577, in _loop_reading
    self._read_fut = self._loop._proactor.recvfrom(self._sock,
                     ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\sertraline\AppData\Local\Programs\Python\Python312\Lib\asyncio\windows_events.py", line 509, in recvfrom
    self._register_with_iocp(conn)
  File "C:\Users\sertraline\AppData\Local\Programs\Python\Python312\Lib\asyncio\windows_events.py", line 709, in _register_with_iocp
    _overlapped.CreateIoCompletionPort(obj.fileno(), self._iocp, 0, 0)
OSError: [WinError 87] The parameter is incorrect
```

**Comment by direct-dok** [comment]
Hello everyone. Tell me if the librespot.core problem has been `solved.Session.SpotifyAuthenticationException: BadCredentials`
Can someone tell me what needs to be done? Thanks for any hints

**Comment by kingosticks** [comment]
Select the running librespot instance in your Spotify client. You should find it in the list of Spotify Connect devices in Spotify's client. That device menu is at the bottom of their app on the currently playing bar, it has a speaker/computer icon. 

Selecting the librespot instance will send the required auth data to the Zeroconf server where it can be stored and reused indefinitely.

**Comment by clemwo** [comment]
> **Login with username/password via `.user_pass()` method is no longer possible: [librespot-org/librespot#1308 (comment)](https://github.com/librespot-org/librespot/issues/1308#issuecomment-2276196094)**
> 
> > Please provide the instructions on how to use Zeroconf instead of Session?
> 
> @pdtan you may use [this very sketchy code](https://gist.github.com/g42ftw/b61304497cb19564e89f50197cf4d730) to generate credentials file to use further. Notice that device running the script should be on the same network as a desktop client in order to transfer playback or/and grab session
> 
> Use `.stored_file()` method instead or `.user_pass()` on [session builder stage](https://github.com/kokarare1212/librespot-python?tab=readme-ov-file#get-spotifys-oauth-token) to load login credentials from local file:
> 
> ```python
> session = Session.Builder() \
>     .stored_file() \
>     .create()
> ```
> 
> It should use `credentials.json` from current working directory by default.

Unfortunately this code doesn't work when run in asyncio. 

I get the following error:

```Traceback (most recent call last):
  File "/Users/clemens/reps/carrotify/.venv/lib/python3.12/site-packages/zeroconf/_utils/asyncio.py", line 86, in run_coro_with_timeout
    return asyncio.run_coroutine_threadsafe(aw, loop).result(
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/homebrew/Cellar/python@3.12/3.12.4/Frameworks/Python.framework/Versions/3.12/lib/python3.12/concurrent/futures/_base.py", line 458, in result
    raise TimeoutError()
TimeoutError
```

Does anyone have an idea on how to adjust the code to make it run in async?

**Comment by shuttie** [comment]
This tool helped me to generate the `credentials.json`: https://github.com/dspearson/librespot-auth

**Comment by greffgreff** [comment]
I can confirm that username and password is still possible with mobile authentication shenanigans. `librespot-js` seems to be working for me: https://git.gay/h/librespot-js/src/branch/main/src/login5.ts

**Comment by jakiepari** [comment]
> This tool helped me to generate the `credentials.json`: https://github.com/dspearson/librespot-auth

i'm using that tool and finally grabbed the credentials.json. but i try with this my code 
```
from librespot.core import Session
from librespot.metadata import TrackId
from librespot.audio.decoders import AudioQuality
import os

try:
    session = Session.Builder().stored_file("./credentials.json").create()
except Exception as e:
    print(f"Error creating session: {e}")
    print("Credentials not found or invalid. Please run the credentials.json creation script first.")
    exit(1)

try:
    track = session.content_feeder().load(TrackId.from_uri("spotify:track:7KA4W4McWYRpgf0fWsJZWB"), AudioQuality.HIGH, False, None)
    audio_stream = track.input_stream
except Exception as e:
    print(f"Error loading track: {e}")
```
its always giving: Error creating session: You must select an authentication method. how to use credentials.json? thank you :D

**Comment by moejoe95** [comment]
> > This tool helped me to generate the `credentials.json`: https://github.com/dspearson/librespot-auth
> 
> i'm using that tool and finally grabbed the credentials.json. but i try with this my code
> 
> ```
> from librespot.core import Session
> from librespot.metadata import TrackId
> from librespot.audio.decoders import AudioQuality
> import os
> 
> try:
>     session = Session.Builder().stored_file("./credentials.json").create()
> except Exception as e:
>     print(f"Error creating session: {e}")
>     print("Credentials not found or invalid. Please run the credentials.json creation script first.")
>     exit(1)
> 
> try:
>     track = session.content_feeder().load(TrackId.from_uri("spotify:track:7KA4W4McWYRpgf0fWsJZWB"), AudioQuality.HIGH, False, None)
>     audio_stream = track.input_stream
> except Exception as e:
>     print(f"Error loading track: {e}")
> ```
> 
> its always giving: Error creating session: You must select an authentication method. how to use credentials.json? thank you :D

Got the same error. Looks like the credential file has changed its format. In the source code it is expected that the json contains `type`, `username`, `credentials`, see [here](https://github.com/kokarare1212/librespot-python/blob/main/librespot/core.py#L1588). However, in the file i got from [librespot-auth](https://github.com/dspearson/librespot-auth) the fields are named `auth_type` and `auth_data`. Renaming the fields in the file fixed the issue for me.

**Comment by jakiepari** [comment]
> > > This tool helped me to generate the `credentials.json`: https://github.com/dspearson/librespot-auth
> > 
> > 
> > i'm using that tool and finally grabbed the credentials.json. but i try with this my code
> > ```
> > from librespot.core import Session
> > from librespot.metadata import TrackId
> > from librespot.audio.decoders import AudioQuality
> > import os
> > 
> > try:
> >     session = Session.Builder().stored_file("./credentials.json").create()
> > except Exception as e:
> >     print(f"Error creating session: {e}")
> >     print("Credentials not found or invalid. Please run the credentials.json creation script first.")
> >     exit(1)
> > 
> > try:
> >     track = session.content_feeder().load(TrackId.from_uri("spotify:track:7KA4W4McWYRpgf0fWsJZWB"), AudioQuality.HIGH, False, None)
> >     audio_stream = track.input_stream
> > except Exception as e:
> >     print(f"Error loading track: {e}")
> > ```
> > 
> > 
> >     
> >       
> >     
> > 
> >       
> >     
> > 
> >     
> >   
> > its always giving: Error creating session: You must select an authentication method. how to use credentials.json? thank you :D
> 
> Got the same error. Looks like the credential file has changed its format. In the source code it is expected that the json contains `type`, `username`, `credentials`, see [here](https://github.com/kokarare1212/librespot-python/blob/main/librespot/core.py#L1588). However, in the file i got from [librespot-auth](https://github.com/dspearson/librespot-auth) the fields are named `auth_type` and `auth_data`. Renaming the fields in the file fixed the issue for me.

I'm trying to rename it. but what should i fill in the type? :D btw thank you for this solution

**Comment by moejoe95** [comment]
> > > > This tool helped me to generate the `credentials.json`: https://github.com/dspearson/librespot-auth
> > > 
> > > 
> > > i'm using that tool and finally grabbed the credentials.json. but i try with this my code
> > > ```
> > > from librespot.core import Session
> > > from librespot.metadata import TrackId
> > > from librespot.audio.decoders import AudioQuality
> > > import os
> > > 
> > > try:
> > >     session = Session.Builder().stored_file("./credentials.json").create()
> > > except Exception as e:
> > >     print(f"Error creating session: {e}")
> > >     print("Credentials not found or invalid. Please run the credentials.json creation script first.")
> > >     exit(1)
> > > 
> > > try:
> > >     track = session.content_feeder().load(TrackId.from_uri("spotify:track:7KA4W4McWYRpgf0fWsJZWB"), AudioQuality.HIGH, False, None)
> > >     audio_stream = track.input_stream
> > > except Exception as e:
> > >     print(f"Error loading track: {e}")
> > > ```
> > > 
> > > 
> > >     
> > >       
> > >     
> > > 
> > >       
> > >     
> > > 
> > >     
> > >   
> > > its always giving: Error creating session: You must select an authentication method. how to use credentials.json? thank you :D
> > 
> > 
> > Got the same error. Looks like the credential file has changed its format. In the source code it is expected that the json contains `type`, `username`, `credentials`, see [here](https://github.com/kokarare1212/librespot-python/blob/main/librespot/core.py#L1588). However, in the file i got from [librespot-auth](https://github.com/dspearson/librespot-auth) the fields are named `auth_type` and `auth_data`. Renaming the fields in the file fixed the issue for me.
> 
> I'm trying to rename it. but what should i fill in the type? :D btw thank you for this solution

Should be a Enum value as defined [here](https://github.com/kokarare1212/librespot-python/blob/main/librespot/proto/Authentication_pb2.py#L24). I used `AUTHENTICATION_STORED_SPOTIFY_CREDENTIALS`.

**Comment by jakiepari** [comment]
> > > > > This tool helped me to generate the `credentials.json`: https://github.com/dspearson/librespot-auth
> > > > 
> > > > 
> > > > i'm using that tool and finally grabbed the credentials.json. but i try with this my code
> > > > ```
> > > > from librespot.core import Session
> > > > from librespot.metadata import TrackId
> > > > from librespot.audio.decoders import AudioQuality
> > > > import os
> > > > 
> > > > try:
> > > >     session = Session.Builder().stored_file("./credentials.json").create()
> > > > except Exception as e:
> > > >     print(f"Error creating session: {e}")
> > > >     print("Credentials not found or invalid. Please run the credentials.json creation script first.")
> > > >     exit(1)
> > > > 
> > > > try:
> > > >     track = session.content_feeder().load(TrackId.from_uri("spotify:track:7KA4W4McWYRpgf0fWsJZWB"), AudioQuality.HIGH, False, None)
> > > >     audio_stream = track.input_stream
> > > > except Exception as e:
> > > >     print(f"Error loading track: {e}")
> > > > ```
> > > > 
> > > > 
> > > >     
> > > >       
> > > >     
> > > > 
> > > >       
> > > >     
> > > > 
> > > >     
> > > >   
> > > > its always giving: Error creating session: You must select an authentication method. how to use credentials.json? thank you :D
> > > 
> > > 
> > > Got the same error. Looks like the credential file has changed its format. In the source code it is expected that the json contains `type`, `username`, `credentials`, see [here](https://github.com/kokarare1212/librespot-python/blob/main/librespot/core.py#L1588). However, in the file i got from [librespot-auth](https://github.com/dspearson/librespot-auth) the fields are named `auth_type` and `auth_data`. Renaming the fields in the file fixed the issue for me.
> > 
> > 
> > I'm trying to rename it. but what should i fill in the type? :D btw thank you for this solution
> 
> Should be a Enum value as defined [here](https://github.com/kokarare1212/librespot-python/blob/main/librespot/proto/Authentication_pb2.py#L24). I used `AUTHENTICATION_STORED_SPOTIFY_CREDENTIALS`.

for example i try with this format: {"type":1,"username":"numberi","credentials":"string"}. and i try to use enum value defined 1 and its giving error: Error: Enum AuthenticationType has no value defined for name 1. how to use the value?

**Comment by moejoe95** [comment]
> > > > > > This tool helped me to generate the `credentials.json`: https://github.com/dspearson/librespot-auth
> > > > > 
> > > > > 
> > > > > i'm using that tool and finally grabbed the credentials.json. but i try with this my code
> > > > > ```
> > > > > from librespot.core import Session
> > > > > from librespot.metadata import TrackId
> > > > > from librespot.audio.decoders import AudioQuality
> > > > > import os
> > > > > 
> > > > > try:
> > > > >     session = Session.Builder().stored_file("./credentials.json").create()
> > > > > except Exception as e:
> > > > >     print(f"Error creating session: {e}")
> > > > >     print("Credentials not found or invalid. Please run the credentials.json creation script first.")
> > > > >     exit(1)
> > > > > 
> > > > > try:
> > > > >     track = session.content_feeder().load(TrackId.from_uri("spotify:track:7KA4W4McWYRpgf0fWsJZWB"), AudioQuality.HIGH, False, None)
> > > > >     audio_stream = track.input_stream
> > > > > except Exception as e:
> > > > >     print(f"Error loading track: {e}")
> > > > > ```
> > > > > 
> > > > > 
> > > > >     
> > > > >       
> > > > >     
> > > > > 
> > > > >       
> > > > >     
> > > > > 
> > > > >     
> > > > >   
> > > > > its always giving: Error creating session: You must select an authentication method. how to use credentials.json? thank you :D
> > > > 
> > > > 
> > > > Got the same error. Looks like the credential file has changed its format. In the source code it is expected that the json contains `type`, `username`, `credentials`, see [here](https://github.com/kokarare1212/librespot-python/blob/main/librespot/core.py#L1588). However, in the file i got from [librespot-auth](https://github.com/dspearson/librespot-auth) the fields are named `auth_type` and `auth_data`. Renaming the fields in the file fixed the issue for me.
> > > 
> > > 
> > > I'm trying to rename it. but what should i fill in the type? :D btw thank you for this solution
> > 
> > 
> > Should be a Enum value as defined [here](https://github.com/kokarare1212/librespot-python/blob/main/librespot/proto/Authentication_pb2.py#L24). I used `AUTHENTICATION_STORED_SPOTIFY_CREDENTIALS`.
> 
> for example i try with this format: {"type":1,"username":"numberi","credentials":"string"}. and i try to use enum value defined 1 and its giving error: Error: Enum AuthenticationType has no value defined for name 1. how to use the value?

use it like this: `"type":"AUTHENTICATION_STORED_SPOTIFY_CREDENTIALS"`

**Comment by root4loot** [comment]
Same issue with username/password auth. As a workaround, I got it to work with OAuth credentials from Rust librespot. 

See pull #314 which adds support for this in stored_file().
