### ISSUE TITLE
[FEATURE REQUEST] Add support for streaming podcasts please :)

### ISSUE THREAD

**Issue by Footsiefat** [kokarare1212/librespot-python#82]
Not much more to this feature request than specified in the title ^ :+1:

**Comment by Footsiefat** [comment]
```
  File "/home/james/Documents/programs/python/spotify_testing/spotify_testing.py", line 169, in client
    stream = SESSION.content_feeder().load(episode_id, VorbisOnlyAudioQuality(QUALITY), False, None)
  File "/home/james/.local/lib/python3.9/site-packages/librespot/audio/__init__.py", line 722, in load
    return self.load_episode(playable_id, audio_quality_picker,
  File "/home/james/.local/lib/python3.9/site-packages/librespot/audio/__init__.py", line 754, in load_episode
    return CdnFeedHelper.load_episode_external(self.__session, episode,
  File "/home/james/.local/lib/python3.9/site-packages/librespot/audio/__init__.py", line 366, in load_episode_external
    streamer = session.cdn().stream_external_episode(
  File "/home/james/.local/lib/python3.9/site-packages/librespot/audio/__init__.py", line 429, in stream_external_episode
    StreamId(episode),
  File "/home/james/.local/lib/python3.9/site-packages/librespot/audio/__init__.py", line 879, in __init__
    self.file_id = None if file is None else file.file_id
AttributeError: 'Episode' object has no attribute 'file_id'
```
I get this error while trying to load the following episode:
[https://open.spotify.com/episode/3u0krXMhLcdGZUZkDVmMSt](https://open.spotify.com/episode/3u0krXMhLcdGZUZkDVmMSt)

**Comment by Footsiefat** [comment]
```
Traceback (most recent call last):
  File "/home/james/Documents/programs/python/spotify_testing/spotify_testing.py", line 529, in <module>
    main()
  File "/home/james/Documents/programs/python/spotify_testing/spotify_testing.py", line 525, in main
    client()
  File "/home/james/Documents/programs/python/spotify_testing/spotify_testing.py", line 169, in client
    stream = SESSION.content_feeder().load(episode_id, VorbisOnlyAudioQuality(QUALITY), False, None)
  File "/home/james/.local/lib/python3.9/site-packages/librespot/audio/__init__.py", line 722, in load
    return self.load_episode(playable_id, audio_quality_picker,
  File "/home/james/.local/lib/python3.9/site-packages/librespot/audio/__init__.py", line 754, in load_episode
    return CdnFeedHelper.load_episode_external(self.__session, episode,
  File "/home/james/.local/lib/python3.9/site-packages/librespot/audio/__init__.py", line 366, in load_episode_external
    streamer = session.cdn().stream_external_episode(
  File "/home/james/.local/lib/python3.9/site-packages/librespot/audio/__init__.py", line 427, in stream_external_episode
    return CdnManager.Streamer(
  File "/home/james/.local/lib/python3.9/site-packages/librespot/audio/__init__.py", line 577, in __init__
    self.write_chunk(first_chunk, 0, False)
  File "/home/james/.local/lib/python3.9/site-packages/librespot/audio/__init__.py", line 586, in write_chunk
    self.buffer[chunk_index] = self.__audio_decrypt.decrypt_chunk(
  File "/home/james/.local/lib/python3.9/site-packages/librespot/structure.py", line 67, in decrypt_chunk
    raise NotImplementedError
NotImplementedError
```

**Comment by kokarare1212** [comment]
It seems that the NoopAudioDecrypt class was not implemented.
It was fixed in the following commit.
c5db0a84a825f97da38d405653e0dae4b4e04850

**Comment by Footsiefat** [comment]
```
Traceback (most recent call last):
  File "/home/james/Documents/programs/python/spotify_testing/./spotify_testing.py", line 544, in <module>
    main()
  File "/home/james/Documents/programs/python/spotify_testing/./spotify_testing.py", line 540, in main
    client()
  File "/home/james/Documents/programs/python/spotify_testing/./spotify_testing.py", line 169, in client
    stream = SESSION.content_feeder().load(
  File "/home/james/.local/lib/python3.9/site-packages/librespot/audio/__init__.py", line 722, in load
    return self.load_episode(playable_id, audio_quality_picker,
  File "/home/james/.local/lib/python3.9/site-packages/librespot/audio/__init__.py", line 752, in load_episode
    episode = self.__session.api().get_metadata_4_episode(episode_id)
  File "/home/james/.local/lib/python3.9/site-packages/librespot/core.py", line 105, in get_metadata_4_episode
    ApiClient.StatusCodeException.check_status(response)
  File "/home/james/.local/lib/python3.9/site-packages/librespot/core.py", line 160, in check_status
    raise ApiClient.StatusCodeException(response)
librespot.core.StatusCodeException: 451
```

**Comment by Footsiefat** [comment]
Ah I see! Turns out doing a api request about that episode before attempting to stream will return a 404 error so I can use that to check before trying to stream :)

Thanks for all the help as always!!
